"""extend user model

Revision ID: 2fc1d3a70cb3
Revises: None
Create Date: 2016-08-22 12:25:20.885080

"""

# revision identifiers, used by Alembic.
revision = '2fc1d3a70cb3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    ### end Alembic commands ###
