"""permissions

Revision ID: 386969013fc3
Revises: feba7869ff72
Create Date: 2016-08-22 17:47:57.270148

"""

# revision identifiers, used by Alembic.
revision = '386969013fc3'
down_revision = 'feba7869ff72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('roles', 'permission')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permission', sa.INTEGER(), nullable=True))
    op.drop_column('roles', 'permissions')
    ### end Alembic commands ###
