"""confirmation email

Revision ID: 6e9fb7255b1c
Revises: 2fc1d3a70cb3
Create Date: 2016-08-22 15:23:35.770281

"""

# revision identifiers, used by Alembic.
revision = '6e9fb7255b1c'
down_revision = '2fc1d3a70cb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
