"""markdown editor

Revision ID: f6303907cb4e
Revises: 83591f1601f6
Create Date: 2016-08-24 18:15:20.945136

"""

# revision identifiers, used by Alembic.
revision = 'f6303907cb4e'
down_revision = '83591f1601f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
